steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package']
    dir: '.'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/java11-example', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/java11-example']

options:
  logging: GCS_ONLY
  logsBucket: "gs://terraformgcpow23"

images:
  - 'gcr.io/$PROJECT_ID/java11-example'
